// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: broadcast/broadcast.proto

package broadcast

import (
	protocol "github.com/livekit/psrpc/examples/pubsub/protocol/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BroadCastReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proto         *protocol.Proto        `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadCastReq) Reset() {
	*x = BroadCastReq{}
	mi := &file_broadcast_broadcast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadCastReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadCastReq) ProtoMessage() {}

func (x *BroadCastReq) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_broadcast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadCastReq.ProtoReflect.Descriptor instead.
func (*BroadCastReq) Descriptor() ([]byte, []int) {
	return file_broadcast_broadcast_proto_rawDescGZIP(), []int{0}
}

func (x *BroadCastReq) GetProto() *protocol.Proto {
	if x != nil {
		return x.Proto
	}
	return nil
}

type BroadCastReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadCastReply) Reset() {
	*x = BroadCastReply{}
	mi := &file_broadcast_broadcast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadCastReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadCastReply) ProtoMessage() {}

func (x *BroadCastReply) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_broadcast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadCastReply.ProtoReflect.Descriptor instead.
func (*BroadCastReply) Descriptor() ([]byte, []int) {
	return file_broadcast_broadcast_proto_rawDescGZIP(), []int{1}
}

func (x *BroadCastReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BroadCastReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BroadCastReply) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

var File_broadcast_broadcast_proto protoreflect.FileDescriptor

const file_broadcast_broadcast_proto_rawDesc = "" +
	"\n" +
	"\x19broadcast/broadcast.proto\x12\bprotocol\x1a\x17protocol/protocol.proto\"5\n" +
	"\fBroadCastReq\x12%\n" +
	"\x05proto\x18\x01 \x01(\v2\x0f.protocol.ProtoR\x05proto\"J\n" +
	"\x0eBroadCastReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc2K\n" +
	"\n" +
	"PushServer\x12=\n" +
	"\tBroadcast\x12\x16.protocol.BroadCastReq\x1a\x18.protocol.BroadCastReplyBGZEgithub.com/livekit/psrpc/examples/pubsub/protocol/broadcast;broadcastb\x06proto3"

var (
	file_broadcast_broadcast_proto_rawDescOnce sync.Once
	file_broadcast_broadcast_proto_rawDescData []byte
)

func file_broadcast_broadcast_proto_rawDescGZIP() []byte {
	file_broadcast_broadcast_proto_rawDescOnce.Do(func() {
		file_broadcast_broadcast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_broadcast_broadcast_proto_rawDesc), len(file_broadcast_broadcast_proto_rawDesc)))
	})
	return file_broadcast_broadcast_proto_rawDescData
}

var file_broadcast_broadcast_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_broadcast_broadcast_proto_goTypes = []any{
	(*BroadCastReq)(nil),   // 0: protocol.BroadCastReq
	(*BroadCastReply)(nil), // 1: protocol.BroadCastReply
	(*protocol.Proto)(nil), // 2: protocol.Proto
}
var file_broadcast_broadcast_proto_depIdxs = []int32{
	2, // 0: protocol.BroadCastReq.proto:type_name -> protocol.Proto
	0, // 1: protocol.PushServer.Broadcast:input_type -> protocol.BroadCastReq
	1, // 2: protocol.PushServer.Broadcast:output_type -> protocol.BroadCastReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_broadcast_broadcast_proto_init() }
func file_broadcast_broadcast_proto_init() {
	if File_broadcast_broadcast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_broadcast_broadcast_proto_rawDesc), len(file_broadcast_broadcast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_broadcast_broadcast_proto_goTypes,
		DependencyIndexes: file_broadcast_broadcast_proto_depIdxs,
		MessageInfos:      file_broadcast_broadcast_proto_msgTypes,
	}.Build()
	File_broadcast_broadcast_proto = out.File
	file_broadcast_broadcast_proto_goTypes = nil
	file_broadcast_broadcast_proto_depIdxs = nil
}
