// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: controller.proto

package controller

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== Room Management ==========
type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *JoinRoomRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinRoomRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RoomInfo      *RoomInfo              `protobuf:"bytes,3,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{1}
}

func (x *JoinRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinRoomResponse) GetRoomInfo() *RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type LeaveRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomResponse) Reset() {
	*x = LeaveRoomResponse{}
	mi := &file_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomResponse) ProtoMessage() {}

func (x *LeaveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaveRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRoomInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomInfoRequest) Reset() {
	*x = GetRoomInfoRequest{}
	mi := &file_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomInfoRequest) ProtoMessage() {}

func (x *GetRoomInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomInfoRequest.ProtoReflect.Descriptor instead.
func (*GetRoomInfoRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{4}
}

func (x *GetRoomInfoRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetRoomInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomInfo      *RoomInfo              `protobuf:"bytes,1,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomInfoResponse) Reset() {
	*x = GetRoomInfoResponse{}
	mi := &file_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomInfoResponse) ProtoMessage() {}

func (x *GetRoomInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomInfoResponse.ProtoReflect.Descriptor instead.
func (*GetRoomInfoResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{5}
}

func (x *GetRoomInfoResponse) GetRoomInfo() *RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

type GetUserNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserNodeRequest) Reset() {
	*x = GetUserNodeRequest{}
	mi := &file_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserNodeRequest) ProtoMessage() {}

func (x *GetUserNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserNodeRequest.ProtoReflect.Descriptor instead.
func (*GetUserNodeRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserNodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeAddress   string                 `protobuf:"bytes,2,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	RoomId        string                 `protobuf:"bytes,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 用户所在房间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserNodeResponse) Reset() {
	*x = GetUserNodeResponse{}
	mi := &file_controller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserNodeResponse) ProtoMessage() {}

func (x *GetUserNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserNodeResponse.ProtoReflect.Descriptor instead.
func (*GetUserNodeResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetUserNodeResponse) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *GetUserNodeResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetUserNodeResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetRoomStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomStatsRequest) Reset() {
	*x = GetRoomStatsRequest{}
	mi := &file_controller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomStatsRequest) ProtoMessage() {}

func (x *GetRoomStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomStatsRequest.ProtoReflect.Descriptor instead.
func (*GetRoomStatsRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{8}
}

type GetRoomStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalRooms    int32                  `protobuf:"varint,1,opt,name=total_rooms,json=totalRooms,proto3" json:"total_rooms,omitempty"`
	TotalUsers    int32                  `protobuf:"varint,2,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	Rooms         []*RoomStats           `protobuf:"bytes,3,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomStatsResponse) Reset() {
	*x = GetRoomStatsResponse{}
	mi := &file_controller_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomStatsResponse) ProtoMessage() {}

func (x *GetRoomStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomStatsResponse.ProtoReflect.Descriptor instead.
func (*GetRoomStatsResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{9}
}

func (x *GetRoomStatsResponse) GetTotalRooms() int32 {
	if x != nil {
		return x.TotalRooms
	}
	return 0
}

func (x *GetRoomStatsResponse) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *GetRoomStatsResponse) GetRooms() []*RoomStats {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// ========== Common Types ==========
type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Users         []*UserInfo            `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Metadata      *RoomMetadata          `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_controller_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{10}
}

func (x *RoomInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomInfo) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *RoomInfo) GetMetadata() *RoomMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RoomInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RoomInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	JoinedAt      int64                  `protobuf:"varint,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_controller_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{11}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UserInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UserInfo) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

type RoomMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	MaxUsers      int32                  `protobuf:"varint,3,opt,name=max_users,json=maxUsers,proto3" json:"max_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMetadata) Reset() {
	*x = RoomMetadata{}
	mi := &file_controller_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMetadata) ProtoMessage() {}

func (x *RoomMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMetadata.ProtoReflect.Descriptor instead.
func (*RoomMetadata) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{12}
}

func (x *RoomMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoomMetadata) GetMaxUsers() int32 {
	if x != nil {
		return x.MaxUsers
	}
	return 0
}

type RoomStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserCount     int32                  `protobuf:"varint,2,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomStats) Reset() {
	*x = RoomStats{}
	mi := &file_controller_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStats) ProtoMessage() {}

func (x *RoomStats) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStats.ProtoReflect.Descriptor instead.
func (*RoomStats) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{13}
}

func (x *RoomStats) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomStats) GetUserCount() int32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *RoomStats) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_controller_proto protoreflect.FileDescriptor

const file_controller_proto_rawDesc = "" +
	"\n" +
	"\x10controller.proto\x12\x06pubsub\"\xf9\x01\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12A\n" +
	"\bmetadata\x18\x05 \x03(\v2%.pubsub.JoinRoomRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\x10JoinRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\troom_info\x18\x03 \x01(\v2\x10.pubsub.RoomInfoR\broomInfo\"D\n" +
	"\x10LeaveRoomRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"G\n" +
	"\x11LeaveRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x12GetRoomInfoRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"D\n" +
	"\x13GetRoomInfoResponse\x12-\n" +
	"\troom_info\x18\x01 \x01(\v2\x10.pubsub.RoomInfoR\broomInfo\"-\n" +
	"\x12GetUserNodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x80\x01\n" +
	"\x13GetUserNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\fnode_address\x18\x02 \x01(\tR\vnodeAddress\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x12\x17\n" +
	"\aroom_id\x18\x04 \x01(\tR\x06roomId\"\x15\n" +
	"\x13GetRoomStatsRequest\"\x81\x01\n" +
	"\x14GetRoomStatsResponse\x12\x1f\n" +
	"\vtotal_rooms\x18\x01 \x01(\x05R\n" +
	"totalRooms\x12\x1f\n" +
	"\vtotal_users\x18\x02 \x01(\x05R\n" +
	"totalUsers\x12'\n" +
	"\x05rooms\x18\x03 \x03(\v2\x11.pubsub.RoomStatsR\x05rooms\"\xbb\x01\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12&\n" +
	"\x05users\x18\x02 \x03(\v2\x10.pubsub.UserInfoR\x05users\x120\n" +
	"\bmetadata\x18\x03 \x01(\v2\x14.pubsub.RoomMetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"\xef\x01\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12:\n" +
	"\bmetadata\x18\x04 \x03(\v2\x1e.pubsub.UserInfo.MetadataEntryR\bmetadata\x12\x1b\n" +
	"\tjoined_at\x18\x05 \x01(\x03R\bjoinedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\fRoomMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tmax_users\x18\x03 \x01(\x05R\bmaxUsers\"b\n" +
	"\tRoomStats\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"user_count\x18\x02 \x01(\x05R\tuserCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt2\xef\x02\n" +
	"\x11ControllerService\x12=\n" +
	"\bJoinRoom\x12\x17.pubsub.JoinRoomRequest\x1a\x18.pubsub.JoinRoomResponse\x12@\n" +
	"\tLeaveRoom\x12\x18.pubsub.LeaveRoomRequest\x1a\x19.pubsub.LeaveRoomResponse\x12F\n" +
	"\vGetRoomInfo\x12\x1a.pubsub.GetRoomInfoRequest\x1a\x1b.pubsub.GetRoomInfoResponse\x12F\n" +
	"\vGetUserNode\x12\x1a.pubsub.GetUserNodeRequest\x1a\x1b.pubsub.GetUserNodeResponse\x12I\n" +
	"\fGetRoomStats\x12\x1b.pubsub.GetRoomStatsRequest\x1a\x1c.pubsub.GetRoomStatsResponseBIZGgithub.com/livekit/psrpc/examples/pubsub/protocol/controller;controllerb\x06proto3"

var (
	file_controller_proto_rawDescOnce sync.Once
	file_controller_proto_rawDescData []byte
)

func file_controller_proto_rawDescGZIP() []byte {
	file_controller_proto_rawDescOnce.Do(func() {
		file_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controller_proto_rawDesc), len(file_controller_proto_rawDesc)))
	})
	return file_controller_proto_rawDescData
}

var file_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_controller_proto_goTypes = []any{
	(*JoinRoomRequest)(nil),      // 0: pubsub.JoinRoomRequest
	(*JoinRoomResponse)(nil),     // 1: pubsub.JoinRoomResponse
	(*LeaveRoomRequest)(nil),     // 2: pubsub.LeaveRoomRequest
	(*LeaveRoomResponse)(nil),    // 3: pubsub.LeaveRoomResponse
	(*GetRoomInfoRequest)(nil),   // 4: pubsub.GetRoomInfoRequest
	(*GetRoomInfoResponse)(nil),  // 5: pubsub.GetRoomInfoResponse
	(*GetUserNodeRequest)(nil),   // 6: pubsub.GetUserNodeRequest
	(*GetUserNodeResponse)(nil),  // 7: pubsub.GetUserNodeResponse
	(*GetRoomStatsRequest)(nil),  // 8: pubsub.GetRoomStatsRequest
	(*GetRoomStatsResponse)(nil), // 9: pubsub.GetRoomStatsResponse
	(*RoomInfo)(nil),             // 10: pubsub.RoomInfo
	(*UserInfo)(nil),             // 11: pubsub.UserInfo
	(*RoomMetadata)(nil),         // 12: pubsub.RoomMetadata
	(*RoomStats)(nil),            // 13: pubsub.RoomStats
	nil,                          // 14: pubsub.JoinRoomRequest.MetadataEntry
	nil,                          // 15: pubsub.UserInfo.MetadataEntry
}
var file_controller_proto_depIdxs = []int32{
	14, // 0: pubsub.JoinRoomRequest.metadata:type_name -> pubsub.JoinRoomRequest.MetadataEntry
	10, // 1: pubsub.JoinRoomResponse.room_info:type_name -> pubsub.RoomInfo
	10, // 2: pubsub.GetRoomInfoResponse.room_info:type_name -> pubsub.RoomInfo
	13, // 3: pubsub.GetRoomStatsResponse.rooms:type_name -> pubsub.RoomStats
	11, // 4: pubsub.RoomInfo.users:type_name -> pubsub.UserInfo
	12, // 5: pubsub.RoomInfo.metadata:type_name -> pubsub.RoomMetadata
	15, // 6: pubsub.UserInfo.metadata:type_name -> pubsub.UserInfo.MetadataEntry
	0,  // 7: pubsub.ControllerService.JoinRoom:input_type -> pubsub.JoinRoomRequest
	2,  // 8: pubsub.ControllerService.LeaveRoom:input_type -> pubsub.LeaveRoomRequest
	4,  // 9: pubsub.ControllerService.GetRoomInfo:input_type -> pubsub.GetRoomInfoRequest
	6,  // 10: pubsub.ControllerService.GetUserNode:input_type -> pubsub.GetUserNodeRequest
	8,  // 11: pubsub.ControllerService.GetRoomStats:input_type -> pubsub.GetRoomStatsRequest
	1,  // 12: pubsub.ControllerService.JoinRoom:output_type -> pubsub.JoinRoomResponse
	3,  // 13: pubsub.ControllerService.LeaveRoom:output_type -> pubsub.LeaveRoomResponse
	5,  // 14: pubsub.ControllerService.GetRoomInfo:output_type -> pubsub.GetRoomInfoResponse
	7,  // 15: pubsub.ControllerService.GetUserNode:output_type -> pubsub.GetUserNodeResponse
	9,  // 16: pubsub.ControllerService.GetRoomStats:output_type -> pubsub.GetRoomStatsResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_controller_proto_init() }
func file_controller_proto_init() {
	if File_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_proto_rawDesc), len(file_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_proto_goTypes,
		DependencyIndexes: file_controller_proto_depIdxs,
		MessageInfos:      file_controller_proto_msgTypes,
	}.Build()
	File_controller_proto = out.File
	file_controller_proto_goTypes = nil
	file_controller_proto_depIdxs = nil
}
