// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: broadcast/broadcast.proto

package broadcast

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PushServer_Broadcast_FullMethodName = "/protocol.PushServer/Broadcast"
)

// PushServerClient is the client API for PushServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushServerClient interface {
	// Broadcast send to every entity
	Broadcast(ctx context.Context, in *BroadCastReq, opts ...grpc.CallOption) (*BroadCastReply, error)
}

type pushServerClient struct {
	cc grpc.ClientConnInterface
}

func NewPushServerClient(cc grpc.ClientConnInterface) PushServerClient {
	return &pushServerClient{cc}
}

func (c *pushServerClient) Broadcast(ctx context.Context, in *BroadCastReq, opts ...grpc.CallOption) (*BroadCastReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadCastReply)
	err := c.cc.Invoke(ctx, PushServer_Broadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushServerServer is the server API for PushServer service.
// All implementations must embed UnimplementedPushServerServer
// for forward compatibility.
type PushServerServer interface {
	// Broadcast send to every entity
	Broadcast(context.Context, *BroadCastReq) (*BroadCastReply, error)
	mustEmbedUnimplementedPushServerServer()
}

// UnimplementedPushServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPushServerServer struct{}

func (UnimplementedPushServerServer) Broadcast(context.Context, *BroadCastReq) (*BroadCastReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedPushServerServer) mustEmbedUnimplementedPushServerServer() {}
func (UnimplementedPushServerServer) testEmbeddedByValue()                    {}

// UnsafePushServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushServerServer will
// result in compilation errors.
type UnsafePushServerServer interface {
	mustEmbedUnimplementedPushServerServer()
}

func RegisterPushServerServer(s grpc.ServiceRegistrar, srv PushServerServer) {
	// If the following call pancis, it indicates UnimplementedPushServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PushServer_ServiceDesc, srv)
}

func _PushServer_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadCastReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServerServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushServer_Broadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServerServer).Broadcast(ctx, req.(*BroadCastReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PushServer_ServiceDesc is the grpc.ServiceDesc for PushServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.PushServer",
	HandlerType: (*PushServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Broadcast",
			Handler:    _PushServer_Broadcast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "broadcast/broadcast.proto",
}
